"""10 интов

Revision ID: 82d3452f7269
Revises: cde2ee028e21
Create Date: 2023-08-08 20:04:59.485844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d3452f7269'
down_revision: Union[str, None] = 'cde2ee028e21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cities', ['city'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    op.add_column('weather', sa.Column('day_1', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_2', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_3', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_4', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_5', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_6', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_7', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_8', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_9', sa.Integer(), nullable=True))
    op.add_column('weather', sa.Column('day_10', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'weather', ['city_name'])
    op.drop_column('weather', 'ten_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather', sa.Column('ten_days', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather', type_='unique')
    op.drop_column('weather', 'day_10')
    op.drop_column('weather', 'day_9')
    op.drop_column('weather', 'day_8')
    op.drop_column('weather', 'day_7')
    op.drop_column('weather', 'day_6')
    op.drop_column('weather', 'day_5')
    op.drop_column('weather', 'day_4')
    op.drop_column('weather', 'day_3')
    op.drop_column('weather', 'day_2')
    op.drop_column('weather', 'day_1')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'cities', type_='unique')
    # ### end Alembic commands ###
