"""вернул

Revision ID: d751b3555fd3
Revises: 3d755cc6091c
Create Date: 2023-08-13 20:35:41.081639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd751b3555fd3'
down_revision: Union[str, None] = '3d755cc6091c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cities', 'updated')
    # ### end Alembic commands ###
